
package lipidos1;

/*unit MeasurementUnit;

rule "will execute per each Measurement having ID color"
when
	/measurements[ id == "color", $colorVal : val ]
then
	controlSet.add($colorVal);
end

query FindColor
    $m: /measurements[ id == "color" ]
end*/
unit SpectrumUnit;

rule "Order fatty acids"
when
   $s: /spectrum;
   /spectrum[$s.getPeak(0).getIntensity()>$s.getPeak(1).getIntensity()];
then
    $s.getPeak(0).setPosition(1);
    $s.getPeak(1).setPosition(0);
end

