
package lipidos1;

/*unit MeasurementUnit;

rule "will execute per each Measurement having ID color"
when
	/measurements[ id == "color", $colorVal : val ]
then
	controlSet.add($colorVal);
end

query FindColor
    $m: /measurements[ id == "color" ]
end*/
unit LipidUnit;

rule "Order fatty acids(1,3)"
when
   $l: /lipid[$f1 : chain1, $f3: chain3];
   /lipid[ $f1!=null,$f3!=null,$f1.getIntensity()<$f3.getIntensity(), $l.getType==null]
then
    $l.setChain1($f3);
    $l.setChain3($f1);

end
rule "Order fatty acids(1,2)"
when
   $l: /lipid[$f1 : chain1, $f2: chain2];
   /lipid[ $f1!=null,$f2!=null,$f1.getIntensity()<$f2.getIntensity(), $l.getType==null]
then
    $l.setChain1($f2);
    $l.setChain2($f1);
end
rule "Order fatty acids(2,3)"
when
   $l: /lipid[$f2 : chain2, $f3: chain3];
   /lipid[$f3!=null,$f2!=null,$f2.getIntensity()<$f3.getIntensity(), $l.getType==null]
then
    $l.setChain2($f3);
    $l.setChain3($f2);
end
rule "oPC,pPC,oPE,pPE"
when
    $l: /lipid[$f1 : chain1, $f2: chain2];
    /lipid[$f1!=null,$f2!=null,($f1.getIntensity()*3)<$f2.getIntensity(), $l.getType=="oPC" || $l.getType=="pPC" || $l.getType=="oPE" || $l.getType=="pPE"]
then
    $l.setViability(true);
end

// TODO Miguel -> diferenciar reglas de identificacion del lipido (reglas de mzs, fragmentos, etc..) con reglas de identificacion de posiciones (intensidad)